name: Create release
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-go@v1
      with:
        go-version: '1.13'
    - name: Build
      run: go generate ./... && go build -tags release -o holger-quotes main.go
      env:
        GOOS: linux
        GOARCH: amd64

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@master
      id: bump_version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: patch
        RELEASE_BRANCHES: master

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.bump_version.outputs.new_tag  }}
        release_name: Release ${{ steps.bump_version.outputs.new_tag }}
    
    - name: Upload binary as release atrifact
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./holger-quotes
        asset_name: holger-quotes
        asset_content_type: application/octet-stream